/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package handin2;

import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        /*
         * TODO add denmark-latest.osm, when done 
         */
        //String filename = "data/denmark.osm.zip"; //Add ".obj" for fast loading speeds
        String filename = "../app/data/kbh.osm.obj";
        var model = Model.load(filename);
        var view = new View(model, primaryStage);
        new Controller(model, view);
    }
}
